spring:
  application:
    name: spring-security-jwt-api
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          public:
            key: classpath:app.pub
          private:
            key: classpath:app.key